### PR TITLE
Add feature flags for icon packs

### PR DESCRIPTION
**Pull request by martijnarts**

### CODE REVIEW

**Review by carloskiki — DISMISSED** [review]

**Review by carloskiki — CHANGES_REQUESTED** [review]
You should change the code generation in the `build/` directory so that every library has a feature flag automatically even if we decide to add more libraries in the future.

**Comment by carloskiki** [comment]
After that, running `just build` will regenerate all of the crates.

**Comment by martijnarts** [comment]
Awesome, will finish that work this week!

**Comment by carloskiki** [comment]
If you need help implementing stuff, I'm available!

**Comment by martijnarts** [comment]
That should do it @carloskiki

**Comment by carloskiki** [comment]
@martijnarts Thank you!

I made some bikeshedding changes i.e., I renamed the features to have names such as: "ant-design-icons" instead of simply "ai".

Otherwise, the changes were good!

**Review by carloskiki — APPROVED** [review]
Looks Good!

**Comment by martijnarts** [comment]
Awesome! Glad to have this merged, thanks for the help 🙏🏻

**Pull request merged**
